# Generated by Django 3.2.23 on 2023-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dnyfx3g7s/image/upload/v1700048391/samples/default_profile_kloiiy.jpg', upload_to='images/'),
        ),
    ]
